name: Release Creation

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      # get part of the tag after the `v`
      - name: Extract tag version number
        id: get_version
        uses: battila7/get-version-action@v2

      # Substitute the Manifest and Download URLs in the system.json
      - name: Substitute Manifest and Download Links For Versioned Ones
        id: sub_manifest_link_version
        uses: microsoft/variable-substitution@v1
        with:
          files: 'system.json'
        env:
          version: ${{steps.get_version.outputs.version-without-v}}
          url: https://github.com/${{github.repository}}
          manifest: https://github.com/${{github.repository}}/releases/latest/download/system.json
          download: https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/torgeternity.zip

      # compile packs
      - name: compile packs
        run: npm ci
      - run: npm run build

      # Create a zip file with all files required by the system to add to the release
      - run: |
          zip -r ./torgeternity.zip \
            css/ \
            dice-models/ \
            fonts/ \
            images/ \
            lang/ \
            module/ \
            packs/ \
            templates/ \
            Changelog.md \
            LICENSE \
            system.json \
            template.json

      # Create a release for this specific version
      - name: Update Release with Files
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true # Set this to false if you want to prevent updating existing releases
          name: ${{ github.event.release.name }}
          draft: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './system.json, ./torgeternity.zip'
          tag: ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}
